name: tfg_library
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  shared_preferences: ^2.0.15
  intl: ^0.19.0
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  image_picker: ^1.1.2
  select_dialog: ^2.0.2
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^11.0.0
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
