const lang = {
  "es": {
    "catalog": "Catalogo",
    "profile": "Perfil",
    "userActiveRents": "Prestamos activos",
    "genres": "Géneros",
    "error": "Error",
    "login": "Iniciar Sesión",
    "register": "Registrarse",
    "user": "Usuario",
    "password": "Contraseña",
    "login_createHere": "¿No tienes cuenta? Creala aquí.",
    "login_loginHere": "¿Ya tienes una cuenta? Inicia sesión aquí.",
    "aviable": "Disponible",
    "notAviable": "No disponible",
    "state": "Estado",
    "sinopsis": "Sinopsis",
    "title": "Titulo",
    "author": "Autor",
    "editorial": "Editorial",
    "editorials": "Editoriales",
    "date": "Fecha de publicación",
    "pages": "Nº de páginas",
    "language": "Idioma",
    "isbn": "ISBN",
    "settings": "Ajustes",
    "logout": "Cerrar Sesión",
    "lightTheme": "Tema Claro",
    "darkTheme": "Tema Oscuro",
    "filters": "Filtros",
    "age": "Edad de lectura",
    "category": "Categoria",
    "categories": "Categorias",
    "languages": "Idiomas",
    "cleanFilters": "Eliminar filtros",
    "hScrollTooltip":
        "Shift + rueda del ratón para desplazarte horizontalmente",
    "rentDifDays": "días restantes",
    "espectedAviable": "Disponibilidad esperada",
    "wishlist": "Lista de deseados",
    "waitlist": "Recordatorios",
    "deleteFromList": "Eliminar elemento de la lista",
    "id": "Id",
    "popularBooks": "Libros mas populares",
    "email": "Correo electronico",
    "deleteBookListDialog-title": "Se eliminara el libro de la lista",
    "deleteBookListDialog-content": "¿Estas seguro?",
    "deleteBookListDialog-true": "Eliminar",
    "deleteBookListDialog-false": "Cancelar",
    "wishListToggle-add": "Libro añadido a la lista de deseados",
    "wishListToggle-del": "Libro eliminado de la lista de deseados",
    "waitListToggle-add": "Libro añadido a recordatorios",
    "waitListToggle-del": "Libro eliminado de recordatorios",
    "rentBook": "Nuevo prestamo",
    "bookId": "Identificador del libro",
    "userId": "Identificador del usuario",
    "returnDate": "Fecha de devolución",
    "rentBookLoadBook": "Cargar libro",
    "rentBookLoadBook-error": "No se ha encontrado el libro",
    "rentBookLoadUser": "Cargar usuario",
    "rentBookLoadUser-error": "No se ha encontrado el usuario",
    "rentBookAction": "Realizar prestamo"
  }
};

String getLang(String value) {
  return "${lang["es"]?[value]}";
}
